trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: DOCKER_USERNAME
    value: $(DOCKER_USERNAME)
  - name: DOCKER_PASSWORD
    value: $(DOCKER_PASSWORD)
    
steps:
  # - task: UsePythonVersion@0
  #   inputs:
  #     versionSpec: '3.9'
  #     addToPath: true

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  # # using setup.py to build the package
  # - script: |
  #     python setup.py sdist bdist_wheel
  #   displayName: 'Build package'

  # uding docker to build the image
  - script: |
      docker build -t tiawold/flask_app:1.0 .
    displayName: 'Build Docker image'

  - script: |
      echo "Docker Username: $(DOCKER_USERNAME)"
      echo $(DOCKER_PASSWORD) | docker login -u $(DOCKER_USERNAME) --password-stdin
      docker push tiawold/flask_app:1.0
    displayName: 'Push Docker image to Docker Hub'
    condition: succeeded()

  - script: pytest tests/ --junitxml=test-results.xml --cov=tests/
    displayName: 'Run tests'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: 'test-results.xml'
      testRunTitle: 'Pytest Results'
    condition: succeededOrFailed()
