FROM python:3.9-slim

USER root

# Install dependencies
RUN apt-get update && apt-get install -y \
    unzip \
    curl \
    wget \
    git \
    jq \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /tmp/requirements.txt
COPY hello_world.sh /tmp/hello_world.sh

CMD ["/hello_world.sh"]